<?php
/**
 * DatabaseClusterSpecEngineAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Everest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Percona Everest schema
 *
 * # Authentication All requests to Everest API require `Authorization: Bearer <token>` header with a valid token in plain-text.  The token can be obtained by using `everestctl token reset` which resets the token and prints it to the screen.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Everest\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DatabaseClusterSpecEngineAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionTest Class Doc Comment
 *
 * @category    Class
 * @description If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node.
 * @package     Everest
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DatabaseClusterSpecEngineAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DatabaseClusterSpecEngineAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution"
     */
    public function testDatabaseClusterSpecEngineAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nodeSelectorTerms"
     */
    public function testPropertyNodeSelectorTerms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
