<?php
/**
 * IoK8sApimachineryPkgApisMetaV1ListMetaTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Everest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Percona Everest schema
 *
 * # Authentication All requests to Everest API require `Authorization: Bearer <token>` header with a valid token in plain-text.  The token can be obtained by using `everestctl token reset` which resets the token and prints it to the screen.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Everest\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * IoK8sApimachineryPkgApisMetaV1ListMetaTest Class Doc Comment
 *
 * @category    Class
 * @description ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
 * @package     Everest
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IoK8sApimachineryPkgApisMetaV1ListMetaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IoK8sApimachineryPkgApisMetaV1ListMeta"
     */
    public function testIoK8sApimachineryPkgApisMetaV1ListMeta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "continue"
     */
    public function testPropertyContinue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remainingItemCount"
     */
    public function testPropertyRemainingItemCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "resourceVersion"
     */
    public function testPropertyResourceVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "selfLink"
     */
    public function testPropertySelfLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
