<?php
/**
 * DatabaseClusterBackupApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Everest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Percona Everest schema
 *
 * # Authentication All requests to Everest API require `Authorization: Bearer <token>` header with a valid token in plain-text.  The token can be obtained by using `everestctl token reset` which resets the token and prints it to the screen.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Everest\Test\Api;

use \Everest\Configuration;
use \Everest\ApiException;
use \Everest\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DatabaseClusterBackupApiTest Class Doc Comment
 *
 * @category Class
 * @package  Everest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DatabaseClusterBackupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDatabaseClusterBackup
     *
     * Create a database cluster backup.
     *
     */
    public function testCreateDatabaseClusterBackup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDatabaseClusterBackup
     *
     * Delete the specified cluster backup.
     *
     */
    public function testDeleteDatabaseClusterBackup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDatabaseClusterBackup
     *
     * Returns the specified cluster backup.
     *
     */
    public function testGetDatabaseClusterBackup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDatabaseClusterBackups
     *
     * List of the created database cluster backups.
     *
     */
    public function testListDatabaseClusterBackups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
