<?php

declare(strict_types=1);

/**
 * Percona Everest schema
 *
 * # Authentication All requests to Everest API require `Authorization: Bearer <token>` header with a valid token in plain-text.  The token can be obtained by using `everestctl token reset` which resets the token and prints it to the screen.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Everest\Client;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Everest\ApiException;
use Everest\Configuration;
use Everest\HeaderSelector;
use Everest\ObjectSerializer;

class BackupStorageApi
{
    /**
     * @var array<string, list<string>>
     */
    public const contentTypes = [
        'createBackupStorage' => [
            'application/json',
        ],
        'deleteBackupStorage' => [
            'application/json',
        ],
        'getBackupStorage' => [
            'application/json',
        ],
        'listBackupStorages' => [
            'application/json',
        ],
        'updateBackupStorage' => [
            'application/json',
        ],
    ];

    /**
     * @param int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        private readonly ClientInterface $client = new Client(),
        private readonly Configuration $config = new Configuration(),
        private readonly HeaderSelector $headerSelector = new HeaderSelector(),
        private int $hostIndex = 0,
    ) {
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * createBackupStorage: Create a new backup storage object
     *
     * @param  \Everest\Model\CreateBackupStorageParams $createBackupStorageParams The backup storage object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\BackupStorage|\Everest\Model\Error|\Everest\Model\Error
     */
    public function createBackupStorage(
        mixed $createBackupStorageParams,
        string $contentType = self::contentTypes['createBackupStorage'][0],
    ): mixed {
        list($response) = $this->createBackupStorageWithHttpInfo($createBackupStorageParams, $contentType);

        return $response;
    }

    /**
     * createBackupStorageWithHttpInfo: Create a new backup storage object
     *
     * @param  \Everest\Model\CreateBackupStorageParams $createBackupStorageParams The backup storage object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\BackupStorage|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function createBackupStorageWithHttpInfo(
        mixed $createBackupStorageParams,
        string $contentType = self::contentTypes['createBackupStorage'][0],
    ): array {
        $request = $this->createBackupStorageRequest($createBackupStorageParams, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\BackupStorage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\BackupStorage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\BackupStorage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\BackupStorage';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\BackupStorage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * createBackupStorageAsync: Create a new backup storage object
     *
     * @param  \Everest\Model\CreateBackupStorageParams $createBackupStorageParams The backup storage object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function createBackupStorageAsync(
        mixed $createBackupStorageParams,
        string $contentType = self::contentTypes['createBackupStorage'][0],
    ): PromiseInterface {
        return $this->createBackupStorageAsyncWithHttpInfo($createBackupStorageParams, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * createBackupStorageAsyncWithHttpInfo: Create a new backup storage object
     *
     * @param  \Everest\Model\CreateBackupStorageParams $createBackupStorageParams The backup storage object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function createBackupStorageAsyncWithHttpInfo(
        mixed $createBackupStorageParams,
        string $contentType = self::contentTypes['createBackupStorage'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\BackupStorage';
        $request = $this->createBackupStorageRequest($createBackupStorageParams, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createBackupStorage'
     *
     * @param  \Everest\Model\CreateBackupStorageParams $createBackupStorageParams The backup storage object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function createBackupStorageRequest(
        mixed $createBackupStorageParams,
        string $contentType = self::contentTypes['createBackupStorage'][0],
    ): Request {
        // verify the required parameter 'createBackupStorageParams' is set
        if ($createBackupStorageParams === null || (is_array($createBackupStorageParams) && count($createBackupStorageParams) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $createBackupStorageParams when calling createBackupStorage'
            );
        }

        $resourcePath = '/backup-storages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createBackupStorageParams)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($createBackupStorageParams));
            } else {
                $httpBody = $createBackupStorageParams;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * deleteBackupStorage: Delete the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return void
     */
    public function deleteBackupStorage(
        mixed $name,
        string $contentType = self::contentTypes['deleteBackupStorage'][0],
    ): void {
        $this->deleteBackupStorageWithHttpInfo($name, $contentType);
    }

    /**
     * deleteBackupStorageWithHttpInfo: Delete the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     null,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function deleteBackupStorageWithHttpInfo(
        mixed $name,
        string $contentType = self::contentTypes['deleteBackupStorage'][0],
    ): array {
        $request = $this->deleteBackupStorageRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * deleteBackupStorageAsync: Delete the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function deleteBackupStorageAsync(
        mixed $name,
        string $contentType = self::contentTypes['deleteBackupStorage'][0],
    ): PromiseInterface {
        return $this->deleteBackupStorageAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * deleteBackupStorageAsyncWithHttpInfo: Delete the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function deleteBackupStorageAsyncWithHttpInfo(
        mixed $name,
        string $contentType = self::contentTypes['deleteBackupStorage'][0],
    ): PromiseInterface {
        $returnType = '';
        $request = $this->deleteBackupStorageRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteBackupStorage'
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function deleteBackupStorageRequest(
        mixed $name,
        string $contentType = self::contentTypes['deleteBackupStorage'][0],
    ): Request {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling deleteBackupStorage'
            );
        }

        $resourcePath = '/backup-storages/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * getBackupStorage: Get the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\BackupStorage|\Everest\Model\Error|\Everest\Model\Error
     */
    public function getBackupStorage(
        mixed $name,
        string $contentType = self::contentTypes['getBackupStorage'][0],
    ): mixed {
        list($response) = $this->getBackupStorageWithHttpInfo($name, $contentType);

        return $response;
    }

    /**
     * getBackupStorageWithHttpInfo: Get the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\BackupStorage|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function getBackupStorageWithHttpInfo(
        mixed $name,
        string $contentType = self::contentTypes['getBackupStorage'][0],
    ): array {
        $request = $this->getBackupStorageRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\BackupStorage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\BackupStorage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\BackupStorage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\BackupStorage';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\BackupStorage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * getBackupStorageAsync: Get the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getBackupStorageAsync(
        mixed $name,
        string $contentType = self::contentTypes['getBackupStorage'][0],
    ): PromiseInterface {
        return $this->getBackupStorageAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * getBackupStorageAsyncWithHttpInfo: Get the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getBackupStorageAsyncWithHttpInfo(
        mixed $name,
        string $contentType = self::contentTypes['getBackupStorage'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\BackupStorage';
        $request = $this->getBackupStorageRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBackupStorage'
     *
     * @param  string $name Name of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getBackupStorageRequest(
        mixed $name,
        string $contentType = self::contentTypes['getBackupStorage'][0],
    ): Request {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getBackupStorage'
            );
        }

        $resourcePath = '/backup-storages/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * listBackupStorages: List of the created backup storages
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBackupStorages'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\BackupStorage[]|\Everest\Model\Error|\Everest\Model\Error
     */
    public function listBackupStorages(
        string $contentType = self::contentTypes['listBackupStorages'][0],
    ): mixed {
        list($response) = $this->listBackupStoragesWithHttpInfo($contentType);

        return $response;
    }

    /**
     * listBackupStoragesWithHttpInfo: List of the created backup storages
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBackupStorages'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\BackupStorage[]|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function listBackupStoragesWithHttpInfo(
        string $contentType = self::contentTypes['listBackupStorages'][0],
    ): array {
        $request = $this->listBackupStoragesRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\BackupStorage[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\BackupStorage[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\BackupStorage[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\BackupStorage[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\BackupStorage[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * listBackupStoragesAsync: List of the created backup storages
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBackupStorages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listBackupStoragesAsync(
        string $contentType = self::contentTypes['listBackupStorages'][0],
    ): PromiseInterface {
        return $this->listBackupStoragesAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * listBackupStoragesAsyncWithHttpInfo: List of the created backup storages
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBackupStorages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listBackupStoragesAsyncWithHttpInfo(
        string $contentType = self::contentTypes['listBackupStorages'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\BackupStorage[]';
        $request = $this->listBackupStoragesRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listBackupStorages'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBackupStorages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listBackupStoragesRequest(
        string $contentType = self::contentTypes['listBackupStorages'][0],
    ): Request {
        $resourcePath = '/backup-storages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * updateBackupStorage: Partial update of the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  \Everest\Model\UpdateBackupStorageParams $updateBackupStorageParams The backup storage params. Only the specified fields will be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\BackupStorage|\Everest\Model\Error|\Everest\Model\Error
     */
    public function updateBackupStorage(
        mixed $name,
        mixed $updateBackupStorageParams,
        string $contentType = self::contentTypes['updateBackupStorage'][0],
    ): mixed {
        list($response) = $this->updateBackupStorageWithHttpInfo($name, $updateBackupStorageParams, $contentType);

        return $response;
    }

    /**
     * updateBackupStorageWithHttpInfo: Partial update of the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  \Everest\Model\UpdateBackupStorageParams $updateBackupStorageParams The backup storage params. Only the specified fields will be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBackupStorage'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\BackupStorage|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function updateBackupStorageWithHttpInfo(
        mixed $name,
        mixed $updateBackupStorageParams,
        string $contentType = self::contentTypes['updateBackupStorage'][0],
    ): array {
        $request = $this->updateBackupStorageRequest($name, $updateBackupStorageParams, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\BackupStorage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\BackupStorage' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\BackupStorage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\BackupStorage';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\BackupStorage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * updateBackupStorageAsync: Partial update of the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  \Everest\Model\UpdateBackupStorageParams $updateBackupStorageParams The backup storage params. Only the specified fields will be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateBackupStorageAsync(
        mixed $name,
        mixed $updateBackupStorageParams,
        string $contentType = self::contentTypes['updateBackupStorage'][0],
    ): PromiseInterface {
        return $this->updateBackupStorageAsyncWithHttpInfo($name, $updateBackupStorageParams, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * updateBackupStorageAsyncWithHttpInfo: Partial update of the specified backup storage
     *
     * @param  string $name Name of the backup storage (required)
     * @param  \Everest\Model\UpdateBackupStorageParams $updateBackupStorageParams The backup storage params. Only the specified fields will be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateBackupStorageAsyncWithHttpInfo(
        mixed $name,
        mixed $updateBackupStorageParams,
        string $contentType = self::contentTypes['updateBackupStorage'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\BackupStorage';
        $request = $this->updateBackupStorageRequest($name, $updateBackupStorageParams, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateBackupStorage'
     *
     * @param  string $name Name of the backup storage (required)
     * @param  \Everest\Model\UpdateBackupStorageParams $updateBackupStorageParams The backup storage params. Only the specified fields will be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBackupStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateBackupStorageRequest(
        mixed $name,
        mixed $updateBackupStorageParams,
        string $contentType = self::contentTypes['updateBackupStorage'][0],
    ): Request {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling updateBackupStorage'
            );
        }

        // verify the required parameter 'updateBackupStorageParams' is set
        if ($updateBackupStorageParams === null || (is_array($updateBackupStorageParams) && count($updateBackupStorageParams) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $updateBackupStorageParams when calling updateBackupStorage'
            );
        }

        $resourcePath = '/backup-storages/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateBackupStorageParams)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($updateBackupStorageParams));
            } else {
                $httpBody = $updateBackupStorageParams;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     *
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
