<?php

declare(strict_types=1);

/**
 * Percona Everest schema
 *
 * # Authentication All requests to Everest API require `Authorization: Bearer <token>` header with a valid token in plain-text.  The token can be obtained by using `everestctl token reset` which resets the token and prints it to the screen.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Everest\Client;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Everest\ApiException;
use Everest\Configuration;
use Everest\HeaderSelector;
use Everest\ObjectSerializer;

class DatabaseEngineApi
{
    /**
     * @var array<string, list<string>>
     */
    public const contentTypes = [
        'getDatabaseEngine' => [
            'application/json',
        ],
        'listDatabaseEngines' => [
            'application/json',
        ],
        'updateDatabaseEngine' => [
            'application/json',
        ],
    ];

    /**
     * @param int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        private readonly ClientInterface $client = new Client(),
        private readonly Configuration $config = new Configuration(),
        private readonly HeaderSelector $headerSelector = new HeaderSelector(),
        private int $hostIndex = 0,
    ) {
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * getDatabaseEngine: Get the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDatabaseEngine'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\DatabaseEngine|\Everest\Model\Error|\Everest\Model\Error
     */
    public function getDatabaseEngine(
        mixed $namespace,
        mixed $name,
        string $contentType = self::contentTypes['getDatabaseEngine'][0],
    ): mixed {
        list($response) = $this->getDatabaseEngineWithHttpInfo($namespace, $name, $contentType);

        return $response;
    }

    /**
     * getDatabaseEngineWithHttpInfo: Get the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDatabaseEngine'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\DatabaseEngine|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function getDatabaseEngineWithHttpInfo(
        mixed $namespace,
        mixed $name,
        string $contentType = self::contentTypes['getDatabaseEngine'][0],
    ): array {
        $request = $this->getDatabaseEngineRequest($namespace, $name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\DatabaseEngine' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\DatabaseEngine' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\DatabaseEngine', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\DatabaseEngine';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\DatabaseEngine',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * getDatabaseEngineAsync: Get the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDatabaseEngine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getDatabaseEngineAsync(
        mixed $namespace,
        mixed $name,
        string $contentType = self::contentTypes['getDatabaseEngine'][0],
    ): PromiseInterface {
        return $this->getDatabaseEngineAsyncWithHttpInfo($namespace, $name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * getDatabaseEngineAsyncWithHttpInfo: Get the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDatabaseEngine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getDatabaseEngineAsyncWithHttpInfo(
        mixed $namespace,
        mixed $name,
        string $contentType = self::contentTypes['getDatabaseEngine'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\DatabaseEngine';
        $request = $this->getDatabaseEngineRequest($namespace, $name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDatabaseEngine'
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDatabaseEngine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getDatabaseEngineRequest(
        mixed $namespace,
        mixed $name,
        string $contentType = self::contentTypes['getDatabaseEngine'][0],
    ): Request {
        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling getDatabaseEngine'
            );
        }

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getDatabaseEngine'
            );
        }

        $resourcePath = '/namespaces/{namespace}/database-engines/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * listDatabaseEngines: List of the available database engines
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabaseEngines'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\DatabaseEngineList|\Everest\Model\Error|\Everest\Model\Error
     */
    public function listDatabaseEngines(
        mixed $namespace,
        string $contentType = self::contentTypes['listDatabaseEngines'][0],
    ): mixed {
        list($response) = $this->listDatabaseEnginesWithHttpInfo($namespace, $contentType);

        return $response;
    }

    /**
     * listDatabaseEnginesWithHttpInfo: List of the available database engines
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabaseEngines'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\DatabaseEngineList|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function listDatabaseEnginesWithHttpInfo(
        mixed $namespace,
        string $contentType = self::contentTypes['listDatabaseEngines'][0],
    ): array {
        $request = $this->listDatabaseEnginesRequest($namespace, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\DatabaseEngineList' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\DatabaseEngineList' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\DatabaseEngineList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\DatabaseEngineList';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\DatabaseEngineList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * listDatabaseEnginesAsync: List of the available database engines
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabaseEngines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listDatabaseEnginesAsync(
        mixed $namespace,
        string $contentType = self::contentTypes['listDatabaseEngines'][0],
    ): PromiseInterface {
        return $this->listDatabaseEnginesAsyncWithHttpInfo($namespace, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * listDatabaseEnginesAsyncWithHttpInfo: List of the available database engines
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabaseEngines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listDatabaseEnginesAsyncWithHttpInfo(
        mixed $namespace,
        string $contentType = self::contentTypes['listDatabaseEngines'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\DatabaseEngineList';
        $request = $this->listDatabaseEnginesRequest($namespace, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listDatabaseEngines'
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabaseEngines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listDatabaseEnginesRequest(
        mixed $namespace,
        string $contentType = self::contentTypes['listDatabaseEngines'][0],
    ): Request {
        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling listDatabaseEngines'
            );
        }

        $resourcePath = '/namespaces/{namespace}/database-engines';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * updateDatabaseEngine: Update the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  \Everest\Model\DatabaseEngine $databaseEngine The database cluster object to be updated (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDatabaseEngine'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\DatabaseEngine|\Everest\Model\Error|\Everest\Model\Error
     */
    public function updateDatabaseEngine(
        mixed $namespace,
        mixed $name,
        mixed $databaseEngine,
        string $contentType = self::contentTypes['updateDatabaseEngine'][0],
    ): mixed {
        list($response) = $this->updateDatabaseEngineWithHttpInfo($namespace, $name, $databaseEngine, $contentType);

        return $response;
    }

    /**
     * updateDatabaseEngineWithHttpInfo: Update the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  \Everest\Model\DatabaseEngine $databaseEngine The database cluster object to be updated (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDatabaseEngine'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\DatabaseEngine|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function updateDatabaseEngineWithHttpInfo(
        mixed $namespace,
        mixed $name,
        mixed $databaseEngine,
        string $contentType = self::contentTypes['updateDatabaseEngine'][0],
    ): array {
        $request = $this->updateDatabaseEngineRequest($namespace, $name, $databaseEngine, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\DatabaseEngine' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\DatabaseEngine' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\DatabaseEngine', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\DatabaseEngine';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\DatabaseEngine',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * updateDatabaseEngineAsync: Update the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  \Everest\Model\DatabaseEngine $databaseEngine The database cluster object to be updated (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDatabaseEngine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateDatabaseEngineAsync(
        mixed $namespace,
        mixed $name,
        mixed $databaseEngine,
        string $contentType = self::contentTypes['updateDatabaseEngine'][0],
    ): PromiseInterface {
        return $this->updateDatabaseEngineAsyncWithHttpInfo($namespace, $name, $databaseEngine, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * updateDatabaseEngineAsyncWithHttpInfo: Update the specified database engine
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  \Everest\Model\DatabaseEngine $databaseEngine The database cluster object to be updated (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDatabaseEngine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateDatabaseEngineAsyncWithHttpInfo(
        mixed $namespace,
        mixed $name,
        mixed $databaseEngine,
        string $contentType = self::contentTypes['updateDatabaseEngine'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\DatabaseEngine';
        $request = $this->updateDatabaseEngineRequest($namespace, $name, $databaseEngine, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateDatabaseEngine'
     *
     * @param  string $namespace Name of the namespace (required)
     * @param  string $name Name of the database engine (required)
     * @param  \Everest\Model\DatabaseEngine $databaseEngine The database cluster object to be updated (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDatabaseEngine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateDatabaseEngineRequest(
        mixed $namespace,
        mixed $name,
        mixed $databaseEngine,
        string $contentType = self::contentTypes['updateDatabaseEngine'][0],
    ): Request {
        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling updateDatabaseEngine'
            );
        }

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling updateDatabaseEngine'
            );
        }

        // verify the required parameter 'databaseEngine' is set
        if ($databaseEngine === null || (is_array($databaseEngine) && count($databaseEngine) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $databaseEngine when calling updateDatabaseEngine'
            );
        }

        $resourcePath = '/namespaces/{namespace}/database-engines/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($databaseEngine)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($databaseEngine));
            } else {
                $httpBody = $databaseEngine;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     *
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
