<?php

declare(strict_types=1);

/**
 * Percona Everest schema
 *
 * # Authentication All requests to Everest API require `Authorization: Bearer <token>` header with a valid token in plain-text.  The token can be obtained by using `everestctl token reset` which resets the token and prints it to the screen.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Everest\Client;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Everest\ApiException;
use Everest\Configuration;
use Everest\HeaderSelector;
use Everest\ObjectSerializer;

class MonitoringApi
{
    /**
     * @var array<string, list<string>>
     */
    public const contentTypes = [
        'createMonitoringInstance' => [
            'application/json',
        ],
        'deleteMonitoringInstance' => [
            'application/json',
        ],
        'getMonitoringInstance' => [
            'application/json',
        ],
        'listMonitoringInstances' => [
            'application/json',
        ],
        'updateMonitoringInstance' => [
            'application/json',
        ],
    ];

    /**
     * @param int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        private readonly ClientInterface $client = new Client(),
        private readonly Configuration $config = new Configuration(),
        private readonly HeaderSelector $headerSelector = new HeaderSelector(),
        private int $hostIndex = 0,
    ) {
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * createMonitoringInstance: Create monitoring instance
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  \Everest\Model\MonitoringInstanceCreateParams $monitoringInstanceCreateParams The Monitoring instance object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\MonitoringInstance|\Everest\Model\Error|\Everest\Model\Error
     */
    public function createMonitoringInstance(
        mixed $namespace,
        mixed $monitoringInstanceCreateParams,
        string $contentType = self::contentTypes['createMonitoringInstance'][0],
    ): mixed {
        list($response) = $this->createMonitoringInstanceWithHttpInfo($namespace, $monitoringInstanceCreateParams, $contentType);

        return $response;
    }

    /**
     * createMonitoringInstanceWithHttpInfo: Create monitoring instance
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  \Everest\Model\MonitoringInstanceCreateParams $monitoringInstanceCreateParams The Monitoring instance object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\MonitoringInstance|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function createMonitoringInstanceWithHttpInfo(
        mixed $namespace,
        mixed $monitoringInstanceCreateParams,
        string $contentType = self::contentTypes['createMonitoringInstance'][0],
    ): array {
        $request = $this->createMonitoringInstanceRequest($namespace, $monitoringInstanceCreateParams, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\MonitoringInstance' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\MonitoringInstance' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\MonitoringInstance', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\MonitoringInstanceBaseWithName';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\MonitoringInstance',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * createMonitoringInstanceAsync: Create monitoring instance
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  \Everest\Model\MonitoringInstanceCreateParams $monitoringInstanceCreateParams The Monitoring instance object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function createMonitoringInstanceAsync(
        mixed $namespace,
        mixed $monitoringInstanceCreateParams,
        string $contentType = self::contentTypes['createMonitoringInstance'][0],
    ): PromiseInterface {
        return $this->createMonitoringInstanceAsyncWithHttpInfo($namespace, $monitoringInstanceCreateParams, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * createMonitoringInstanceAsyncWithHttpInfo: Create monitoring instance
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  \Everest\Model\MonitoringInstanceCreateParams $monitoringInstanceCreateParams The Monitoring instance object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function createMonitoringInstanceAsyncWithHttpInfo(
        mixed $namespace,
        mixed $monitoringInstanceCreateParams,
        string $contentType = self::contentTypes['createMonitoringInstance'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\MonitoringInstanceBaseWithName';
        $request = $this->createMonitoringInstanceRequest($namespace, $monitoringInstanceCreateParams, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMonitoringInstance'
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  \Everest\Model\MonitoringInstanceCreateParams $monitoringInstanceCreateParams The Monitoring instance object to be created (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function createMonitoringInstanceRequest(
        mixed $namespace,
        mixed $monitoringInstanceCreateParams,
        string $contentType = self::contentTypes['createMonitoringInstance'][0],
    ): Request {
        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling createMonitoringInstance'
            );
        }

        // verify the required parameter 'monitoringInstanceCreateParams' is set
        if ($monitoringInstanceCreateParams === null || (is_array($monitoringInstanceCreateParams) && count($monitoringInstanceCreateParams) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $monitoringInstanceCreateParams when calling createMonitoringInstance'
            );
        }

        $resourcePath = '/namespaces/{namespace}/monitoring-instances';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($monitoringInstanceCreateParams)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($monitoringInstanceCreateParams));
            } else {
                $httpBody = $monitoringInstanceCreateParams;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * deleteMonitoringInstance: Delete monitoring instnace
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return void
     */
    public function deleteMonitoringInstance(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['deleteMonitoringInstance'][0],
    ): void {
        $this->deleteMonitoringInstanceWithHttpInfo($name, $namespace, $contentType);
    }

    /**
     * deleteMonitoringInstanceWithHttpInfo: Delete monitoring instnace
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     null,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function deleteMonitoringInstanceWithHttpInfo(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['deleteMonitoringInstance'][0],
    ): array {
        $request = $this->deleteMonitoringInstanceRequest($name, $namespace, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * deleteMonitoringInstanceAsync: Delete monitoring instnace
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function deleteMonitoringInstanceAsync(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['deleteMonitoringInstance'][0],
    ): PromiseInterface {
        return $this->deleteMonitoringInstanceAsyncWithHttpInfo($name, $namespace, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * deleteMonitoringInstanceAsyncWithHttpInfo: Delete monitoring instnace
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function deleteMonitoringInstanceAsyncWithHttpInfo(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['deleteMonitoringInstance'][0],
    ): PromiseInterface {
        $returnType = '';
        $request = $this->deleteMonitoringInstanceRequest($name, $namespace, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteMonitoringInstance'
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function deleteMonitoringInstanceRequest(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['deleteMonitoringInstance'][0],
    ): Request {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling deleteMonitoringInstance'
            );
        }

        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling deleteMonitoringInstance'
            );
        }

        $resourcePath = '/namespaces/{namespace}/monitoring-instances/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * getMonitoringInstance: Get monitoring instance
     *
     * @param  string $name Name of the Monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\MonitoringInstance|\Everest\Model\Error|\Everest\Model\Error|\Everest\Model\Error
     */
    public function getMonitoringInstance(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['getMonitoringInstance'][0],
    ): mixed {
        list($response) = $this->getMonitoringInstanceWithHttpInfo($name, $namespace, $contentType);

        return $response;
    }

    /**
     * getMonitoringInstanceWithHttpInfo: Get monitoring instance
     *
     * @param  string $name Name of the Monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\MonitoringInstance|\Everest\Model\Error|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function getMonitoringInstanceWithHttpInfo(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['getMonitoringInstance'][0],
    ): array {
        $request = $this->getMonitoringInstanceRequest($name, $namespace, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\MonitoringInstance' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\MonitoringInstance' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\MonitoringInstance', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\MonitoringInstanceBaseWithName';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\MonitoringInstance',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * getMonitoringInstanceAsync: Get monitoring instance
     *
     * @param  string $name Name of the Monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getMonitoringInstanceAsync(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['getMonitoringInstance'][0],
    ): PromiseInterface {
        return $this->getMonitoringInstanceAsyncWithHttpInfo($name, $namespace, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * getMonitoringInstanceAsyncWithHttpInfo: Get monitoring instance
     *
     * @param  string $name Name of the Monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getMonitoringInstanceAsyncWithHttpInfo(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['getMonitoringInstance'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\MonitoringInstanceBaseWithName';
        $request = $this->getMonitoringInstanceRequest($name, $namespace, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMonitoringInstance'
     *
     * @param  string $name Name of the Monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function getMonitoringInstanceRequest(
        mixed $name,
        mixed $namespace,
        string $contentType = self::contentTypes['getMonitoringInstance'][0],
    ): Request {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getMonitoringInstance'
            );
        }

        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling getMonitoringInstance'
            );
        }

        $resourcePath = '/namespaces/{namespace}/monitoring-instances/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * listMonitoringInstances: List monitoring instances
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMonitoringInstances'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\MonitoringInstance[]|\Everest\Model\Error|\Everest\Model\Error
     */
    public function listMonitoringInstances(
        mixed $namespace,
        string $contentType = self::contentTypes['listMonitoringInstances'][0],
    ): mixed {
        list($response) = $this->listMonitoringInstancesWithHttpInfo($namespace, $contentType);

        return $response;
    }

    /**
     * listMonitoringInstancesWithHttpInfo: List monitoring instances
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMonitoringInstances'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\MonitoringInstance[]|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function listMonitoringInstancesWithHttpInfo(
        mixed $namespace,
        string $contentType = self::contentTypes['listMonitoringInstances'][0],
    ): array {
        $request = $this->listMonitoringInstancesRequest($namespace, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\MonitoringInstance[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\MonitoringInstance[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\MonitoringInstance[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\MonitoringInstance[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\MonitoringInstance[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * listMonitoringInstancesAsync: List monitoring instances
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMonitoringInstances'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listMonitoringInstancesAsync(
        mixed $namespace,
        string $contentType = self::contentTypes['listMonitoringInstances'][0],
    ): PromiseInterface {
        return $this->listMonitoringInstancesAsyncWithHttpInfo($namespace, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * listMonitoringInstancesAsyncWithHttpInfo: List monitoring instances
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMonitoringInstances'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listMonitoringInstancesAsyncWithHttpInfo(
        mixed $namespace,
        string $contentType = self::contentTypes['listMonitoringInstances'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\MonitoringInstance[]';
        $request = $this->listMonitoringInstancesRequest($namespace, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listMonitoringInstances'
     *
     * @param  string $namespace Namespace of the backup storage (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMonitoringInstances'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function listMonitoringInstancesRequest(
        mixed $namespace,
        string $contentType = self::contentTypes['listMonitoringInstances'][0],
    ): Request {
        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling listMonitoringInstances'
            );
        }

        $resourcePath = '/namespaces/{namespace}/monitoring-instances';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * updateMonitoringInstance: Update monitoring instance
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  \Everest\Model\MonitoringInstanceUpdateParams $monitoringInstanceUpdateParams The monitoring instance object to be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \Everest\Model\MonitoringInstance|\Everest\Model\Error|\Everest\Model\Error|\Everest\Model\Error
     */
    public function updateMonitoringInstance(
        mixed $name,
        mixed $namespace,
        mixed $monitoringInstanceUpdateParams,
        string $contentType = self::contentTypes['updateMonitoringInstance'][0],
    ): mixed {
        list($response) = $this->updateMonitoringInstanceWithHttpInfo($name, $namespace, $monitoringInstanceUpdateParams, $contentType);

        return $response;
    }

    /**
     * updateMonitoringInstanceWithHttpInfo: Update monitoring instance
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  \Everest\Model\MonitoringInstanceUpdateParams $monitoringInstanceUpdateParams The monitoring instance object to be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMonitoringInstance'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \Everest\Model\MonitoringInstance|\Everest\Model\Error|\Everest\Model\Error|\Everest\Model\Error,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function updateMonitoringInstanceWithHttpInfo(
        mixed $name,
        mixed $namespace,
        mixed $monitoringInstanceUpdateParams,
        string $contentType = self::contentTypes['updateMonitoringInstance'][0],
    ): array {
        $request = $this->updateMonitoringInstanceRequest($name, $namespace, $monitoringInstanceUpdateParams, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Everest\Model\MonitoringInstance' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\MonitoringInstance' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\MonitoringInstance', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Everest\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Everest\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Everest\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Everest\Model\MonitoringInstanceBaseWithName';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\MonitoringInstance',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Everest\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * updateMonitoringInstanceAsync: Update monitoring instance
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  \Everest\Model\MonitoringInstanceUpdateParams $monitoringInstanceUpdateParams The monitoring instance object to be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateMonitoringInstanceAsync(
        mixed $name,
        mixed $namespace,
        mixed $monitoringInstanceUpdateParams,
        string $contentType = self::contentTypes['updateMonitoringInstance'][0],
    ): PromiseInterface {
        return $this->updateMonitoringInstanceAsyncWithHttpInfo($name, $namespace, $monitoringInstanceUpdateParams, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * updateMonitoringInstanceAsyncWithHttpInfo: Update monitoring instance
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  \Everest\Model\MonitoringInstanceUpdateParams $monitoringInstanceUpdateParams The monitoring instance object to be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateMonitoringInstanceAsyncWithHttpInfo(
        mixed $name,
        mixed $namespace,
        mixed $monitoringInstanceUpdateParams,
        string $contentType = self::contentTypes['updateMonitoringInstance'][0],
    ): PromiseInterface {
        $returnType = '\Everest\Model\MonitoringInstanceBaseWithName';
        $request = $this->updateMonitoringInstanceRequest($name, $namespace, $monitoringInstanceUpdateParams, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMonitoringInstance'
     *
     * @param  string $name Name of the monitoring instance (required)
     * @param  string $namespace Namespace of the Monitoring instance (required)
     * @param  \Everest\Model\MonitoringInstanceUpdateParams $monitoringInstanceUpdateParams The monitoring instance object to be updated. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMonitoringInstance'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function updateMonitoringInstanceRequest(
        mixed $name,
        mixed $namespace,
        mixed $monitoringInstanceUpdateParams,
        string $contentType = self::contentTypes['updateMonitoringInstance'][0],
    ): Request {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling updateMonitoringInstance'
            );
        }

        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling updateMonitoringInstance'
            );
        }

        // verify the required parameter 'monitoringInstanceUpdateParams' is set
        if ($monitoringInstanceUpdateParams === null || (is_array($monitoringInstanceUpdateParams) && count($monitoringInstanceUpdateParams) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $monitoringInstanceUpdateParams when calling updateMonitoringInstance'
            );
        }

        $resourcePath = '/namespaces/{namespace}/monitoring-instances/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($monitoringInstanceUpdateParams)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($monitoringInstanceUpdateParams));
            } else {
                $httpBody = $monitoringInstanceUpdateParams;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     *
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
